version: "1.0"

services:
    catalog-database:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
            MYSQL_DATABASE: foodtotem
            MYSQL_USER: user
            MYSQL_PASSWORD: uSeRpAsSwOrD
        ports:
            - "33061:3306"
        container_name: catalog-database
        networks:
            - foodtotem-network
    catalog-api:
        build:
          context: ../../src
          dockerfile: Dockerfile
        ports:
            - "3003:80"
        environment:
            ConnectionStrings__DefaultConnection: "Server=catalog-database;Port=3306;Database=foodtotem;Uid=user;Pwd=uSeRpAsSwOrD"
        depends_on:
            - catalog-database
        networks:
            - foodtotem-network
        restart: always
networks:
    foodtotem-network:
        driver: bridge

    
    